# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('idfornecedor', models.IntegerField(db_column='idFornecedor', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=45, null=True)),
                ('raz_social', models.CharField(blank=True, max_length=45, null=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('endereco', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(db_column='idPedido', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.IntegerField(db_column='idProduto', primary_key=True, serialize=False)),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('preco', models.CharField(blank=True, max_length=45, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idservico', models.IntegerField(db_column='idServico', primary_key=True, serialize=False)),
                ('os', models.CharField(blank=True, max_length=45, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=45, null=True)),
                ('preco', models.CharField(blank=True, max_length=45, null=True)),
                ('local_execucao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Servico',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('idsolicitante', models.IntegerField(db_column='idSolicitante', primary_key=True, serialize=False)),
                ('sol_empresa', models.CharField(blank=True, max_length=45, null=True)),
                ('sol_telefone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Solicitante',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='idsolicitante',
            field=models.ForeignKey(db_column='idSolicitante', on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.Solicitante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='fornecedores.Produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicos',
            field=models.ManyToManyField(to='fornecedores.Servico'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(to='fornecedores.Produto'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='servicos',
            field=models.ManyToManyField(to='fornecedores.Servico'),
        ),
    ]
