# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('doc_cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('doc_rg', models.CharField(max_length=50, verbose_name='RG')),
                ('doc_crm', models.CharField(max_length=50, verbose_name='CRM')),
                ('doc_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('doc_marital_status', models.CharField(choices=[('0', 'Selecione'), ('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Divorciado')], default='0', max_length=50, verbose_name='Estado Civil')),
                ('doc_sex', models.CharField(choices=[('0', 'Selecione'), ('1', 'Feminino'), ('2', 'Masculino')], default='0', max_length=1, verbose_name='Sexo')),
                ('doc_email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('doc_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('doc_state', models.CharField(max_length=50, verbose_name='Estado')),
                ('doc_city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('doc_street', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('doc_num_street', models.CharField(max_length=50, verbose_name='N\xfamero')),
                ('doc_compl', models.CharField(max_length=50, verbose_name='Complemento')),
                ('paramedic', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
