# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STAMPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('0', 'Selecione'), ('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Divorciado')], default='0', max_length=1)),
                ('sex', models.CharField(choices=[('0', 'Selecione'), ('1', 'Feminino'), ('2', 'Masculino')], default='0', max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('paramedic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stamps',
            },
        ),
    ]
