# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-23 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='Cidade')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('doc_cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('doc_rg', models.CharField(max_length=50, verbose_name='RG')),
                ('doc_crm', models.CharField(max_length=50, verbose_name='CRM')),
                ('doc_birth', models.CharField(max_length=50, verbose_name='Data de Nascimento')),
                ('doc_marital_status', models.CharField(choices=[('0', 'Selecione'), ('1', 'Solteiro'), ('2', 'Casado'), ('3', 'Divorciado')], default='0', max_length=50, verbose_name='Estado Civil')),
                ('doc_sex', models.CharField(choices=[('0', 'Selecione'), ('1', 'Feminino'), ('2', 'Masculino')], default='0', max_length=1, verbose_name='Sexo')),
                ('doc_email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('doc_street', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('doc_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('doc_num_street', models.CharField(max_length=50, verbose_name='N\xfamero')),
                ('doc_compl', models.CharField(max_length=50, verbose_name='Complemento')),
                ('doc_paramedic', models.BooleanField(default=False, verbose_name='Param\xe9dico')),
                ('doc_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.City', verbose_name='Cidade')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Medical_Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_spec_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('med_spec_description', models.CharField(max_length=500, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'db_table': 'medical_specialty',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, verbose_name='Estado')),
                ('state_uf', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_medical_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Medical_Specialty', verbose_name='Especialidade M\xe9dica'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.State', verbose_name='Estado'),
        ),
    ]
