# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-23 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_compl',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
    ]
