# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-23 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20170423_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_compl',
        ),
    ]
