# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='con_entry_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
