# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20170425_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='con_hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Hospital', verbose_name='Hospital'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='con_patient_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='con_triagem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Triagem', verbose_name='Triagem'),
        ),
    ]
