# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_auto_20170425_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='con_doctor_crm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Doctor', verbose_name='M\xe9dico Respons\xe1vel'),
        ),
    ]
