# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20170425_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='tri_consulta',
        ),
        migrations.AddField(
            model_name='triagem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
