# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_auto_20170425_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='tri_enfermeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.Enfermeiro', verbose_name='Enfermeiro Respons\xe1vel'),
        ),
    ]
