# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_auto_20170425_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hos_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
