# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_auto_20170425_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='con_diagnostico',
            field=models.CharField(default='No description', max_length=256, verbose_name='Diagn\xf3stico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='con_evolucao',
            field=models.CharField(default='No evolution', max_length=256, verbose_name='Evolu\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='con_prescricao',
            field=models.CharField(default='No prescription', max_length=256, verbose_name='Prescri\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='con_tratamento',
            field=models.CharField(default='No treatment', max_length=256, verbose_name='Tratamento'),
            preserve_default=False,
        ),
    ]
